# This is a way do build and deploy application for QA - using same Dockerfile which is used to build official image
version: '3'
services:
  server: &server
    build:
      context: ./
    restart: always
    depends_on:
      - db
#   volumes:
#       e.g. to mount LDAP config:
#       - /c/Users/username/dockerdata/clifoobar/ldap_config.py:/app/cfb_server/ldap_config.py
#       - /home/username/dockerdata/clifoobar/ldap_config.py:/app/cfb_server/ldap_config.py
    environment:
      - DJANGO_SECRET_KEY=youshoulddefinetelychangethistosomethingelseandtakecare
      - DJANGO_TIME_ZONE=Europe/Vilnius
      - DJANGO_DB_URL=postgres://postgres@db:5432/postgres
      - DJANGO_ALLOWED_HOSTS=*
      - DEBUG=True
    ports:
      - 10080:80
      - 10443:443
  db:
    image: postgres:10.4-alpine
    restart: always
    volumes:
    - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:

