# This is a way do build and deploy application for QA - using same Dockerfile which is used to build official image
version: '3'
services:
  server: &server
    build:
      context: ./
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 20080:80
      - 20443:443
  db:
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    volumes:
    - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
