# Generated by Django 2.2.7 on 2019-12-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0002_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
