# Generated by Django 2.2.7 on 2019-11-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfb', '0002_snippet_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
